// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class MainWindow {
    
    private Gtk.Action Options;
    
    private Gtk.Action AddFolder;
    
    private Gtk.Action NewCollection;
    
    private Gtk.Action Preferences;
    
    private Gtk.Action Exit1;
    
    private Gtk.Action Update;
    
    private Gtk.ToggleAction Exit2;
    
    private Gtk.Action AddFile;
    
    private Gtk.Action About;
    
    private Gtk.Action About3;
    
    private Gtk.Fixed MainFixedWindow;
    
    private Gtk.Statusbar bottomStatusBar;
    
    private Gtk.MenuBar menubar;
    
    private Gtk.HBox musicButtonBox;
    
    private Gtk.Button playButton;
    
    private Gtk.Button stopButton;
    
    private Gtk.Button previousButton;
    
    private Gtk.Button nextButton;
    
    private Gtk.Button rewindButton;
    
    private Gtk.Button fastfoward;
    
    private Gtk.ProgressBar songProgressBar;
    
    private Gtk.HScale volumeScale;
    
    private Gtk.Button muteButton;
    
    private Gtk.Button volumeButton;
    
    private Gtk.Label npSong;
    
    private Gtk.Label npByFrom;
    
    private Gtk.Image albumCoverImage;
    
    private Gtk.Notebook tabbedNotebook;
    
    private Gtk.VBox searchVertBox;
    
    private Gtk.HBox searchTopHorBox;
    
    private Gtk.ComboBox searchSelectionType;
    
    private Gtk.Entry searchEntry;
    
    private Gtk.ScrolledWindow searchList;
    
    private Gtk.TreeView songListTree;
    
    private Gtk.HBox searchBottomHorizonalBox;
    
    private Gtk.Button searchAddButton;
    
    private Gtk.Label searchMainLabel;
    
    private Gtk.VBox queueVertBox;
    
    private Gtk.ScrolledWindow queueScrolledList;
    
    private Gtk.TreeView queueTreeView;
    
    private Gtk.HBox queueBottomHorBox;
    
    private Gtk.Button queueNewPlaylist;
    
    private Gtk.Button queueDeleteButton;
    
    private Gtk.Label label4;
    
    private Gtk.Entry queueEntryBox;
    
    private Gtk.Button queueSaveButton;
    
    private Gtk.Label queueMainLabel;
    
    private Gtk.VBox playlistVertBox;
    
    private Gtk.ScrolledWindow playListScrolledWindow;
    
    private Gtk.TreeView playListTreeView;
    
    private Gtk.HBox playListBottomBox;
    
    private Gtk.Button playListNewButton;
    
    private Gtk.Button playListLoadButton;
    
    private Gtk.Button playlistRenameButton;
    
    private Gtk.Button playListDeleteButton;
    
    private Gtk.Label playListMainLabel;
    
    protected virtual void Build() {
        Stetic.Gui.Initialize();
        // Widget MainWindow
        Gtk.UIManager w1 = new Gtk.UIManager();
        Gtk.ActionGroup w2 = new Gtk.ActionGroup("Default");
        this.Options = new Gtk.Action("Options", Mono.Unix.Catalog.GetString("Options"), null, "gtk-preferences");
        this.Options.ShortLabel = Mono.Unix.Catalog.GetString("File");
        w2.Add(this.Options, null);
        this.AddFolder = new Gtk.Action("AddFolder", Mono.Unix.Catalog.GetString("Add Folder"), null, "gtk-open");
        this.AddFolder.ShortLabel = Mono.Unix.Catalog.GetString("Add Folder");
        w2.Add(this.AddFolder, null);
        this.NewCollection = new Gtk.Action("NewCollection", Mono.Unix.Catalog.GetString("New Collection"), null, "gtk-new");
        this.NewCollection.ShortLabel = Mono.Unix.Catalog.GetString("New Collection");
        w2.Add(this.NewCollection, null);
        this.Preferences = new Gtk.Action("Preferences", Mono.Unix.Catalog.GetString("Preferences"), null, "gtk-preferences");
        this.Preferences.ShortLabel = Mono.Unix.Catalog.GetString("Options");
        w2.Add(this.Preferences, null);
        this.Exit1 = new Gtk.Action("Exit1", Mono.Unix.Catalog.GetString("Exit"), null, "gtk-quit");
        this.Exit1.ShortLabel = Mono.Unix.Catalog.GetString("Exit");
        w2.Add(this.Exit1, null);
        this.Update = new Gtk.Action("Update", Mono.Unix.Catalog.GetString("Update"), null, "gtk-dialog-warning");
        this.Update.ShortLabel = Mono.Unix.Catalog.GetString("Update");
        w2.Add(this.Update, null);
        this.Exit2 = new Gtk.ToggleAction("Exit2", Mono.Unix.Catalog.GetString("Exit"), null, "gtk-quit");
        this.Exit2.ShortLabel = Mono.Unix.Catalog.GetString("Exit");
        w2.Add(this.Exit2, null);
        this.AddFile = new Gtk.Action("AddFile", Mono.Unix.Catalog.GetString("Add File"), null, "gtk-add");
        this.AddFile.ShortLabel = Mono.Unix.Catalog.GetString("Add File");
        w2.Add(this.AddFile, null);
        this.About = new Gtk.Action("About", Mono.Unix.Catalog.GetString("About"), null, "gtk-about");
        this.About.ShortLabel = Mono.Unix.Catalog.GetString("About");
        w2.Add(this.About, null);
        this.About3 = new Gtk.Action("About3", Mono.Unix.Catalog.GetString("_About"), null, "gtk-about");
        this.About3.ShortLabel = Mono.Unix.Catalog.GetString("_About");
        w2.Add(this.About3, null);
        w1.InsertActionGroup(w2, 0);
        this.AddAccelGroup(w1.AccelGroup);
        this.WidthRequest = 360;
        this.Name = "MainWindow";
        this.Title = Mono.Unix.Catalog.GetString("Mp3 Player");
        this.Icon = Stetic.IconLoader.LoadIcon("stock_headphones", 16);
        this.WindowPosition = ((Gtk.WindowPosition)(4));
        this.Resizable = false;
        this.AllowGrow = false;
        // Container child MainWindow.Gtk.Container+ContainerChild
        this.MainFixedWindow = new Gtk.Fixed();
        this.MainFixedWindow.WidthRequest = 0;
        this.MainFixedWindow.HeightRequest = 640;
        this.MainFixedWindow.Name = "MainFixedWindow";
        this.MainFixedWindow.HasWindow = false;
        // Container child MainFixedWindow.Gtk.Fixed+FixedChild
        this.bottomStatusBar = new Gtk.Statusbar();
        this.bottomStatusBar.WidthRequest = 363;
        this.bottomStatusBar.HeightRequest = 17;
        this.bottomStatusBar.Name = "bottomStatusBar";
        this.bottomStatusBar.Spacing = 6;
        this.MainFixedWindow.Add(this.bottomStatusBar);
        Gtk.Fixed.FixedChild w3 = ((Gtk.Fixed.FixedChild)(this.MainFixedWindow[this.bottomStatusBar]));
        w3.X = 1;
        w3.Y = 624;
        // Container child MainFixedWindow.Gtk.Fixed+FixedChild
        w1.AddUiFromString("<ui><menubar name='menubar'><menu action='Options'><menuitem action='NewCollection'/><menuitem action='AddFolder'/><menuitem action='AddFile'/><menuitem action='Preferences'/><menuitem action='Exit1'/></menu><menu action='About'><menuitem action='About3'/></menu></menubar></ui>");
        this.menubar = ((Gtk.MenuBar)(w1.GetWidget("/menubar")));
        this.menubar.WidthRequest = 370;
        this.menubar.HasDefault = true;
        this.menubar.CanFocus = true;
        this.menubar.Name = "menubar";
        this.MainFixedWindow.Add(this.menubar);
        // Container child MainFixedWindow.Gtk.Fixed+FixedChild
        this.musicButtonBox = new Gtk.HBox();
        this.musicButtonBox.Name = "musicButtonBox";
        this.musicButtonBox.Spacing = 6;
        // Container child musicButtonBox.Gtk.Box+BoxChild
        this.playButton = new Gtk.Button();
        this.playButton.CanFocus = true;
        this.playButton.Name = "playButton";
        this.playButton.UseUnderline = true;
        // Container child playButton.Gtk.Container+ContainerChild
        Gtk.Alignment w5 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        w5.Name = "GtkAlignment";
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w6 = new Gtk.HBox();
        w6.Name = "GtkHBox";
        w6.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w7 = new Gtk.Image();
        w7.Name = "image35";
        w7.Pixbuf = Stetic.IconLoader.LoadIcon("stock_media-play", 16);
        w6.Add(w7);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w9 = new Gtk.Label();
        w9.Name = "GtkLabel";
        w9.LabelProp = "";
        w6.Add(w9);
        w5.Add(w6);
        this.playButton.Add(w5);
        this.musicButtonBox.Add(this.playButton);
        Gtk.Box.BoxChild w13 = ((Gtk.Box.BoxChild)(this.musicButtonBox[this.playButton]));
        w13.Position = 0;
        w13.Expand = false;
        w13.Fill = false;
        // Container child musicButtonBox.Gtk.Box+BoxChild
        this.stopButton = new Gtk.Button();
        this.stopButton.CanFocus = true;
        this.stopButton.Name = "stopButton";
        this.stopButton.UseUnderline = true;
        // Container child stopButton.Gtk.Container+ContainerChild
        Gtk.Alignment w14 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        w14.Name = "GtkAlignment";
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w15 = new Gtk.HBox();
        w15.Name = "GtkHBox";
        w15.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w16 = new Gtk.Image();
        w16.Name = "image36";
        w16.Pixbuf = Stetic.IconLoader.LoadIcon("stock_media-stop", 16);
        w15.Add(w16);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w18 = new Gtk.Label();
        w18.Name = "GtkLabel";
        w18.LabelProp = "";
        w15.Add(w18);
        w14.Add(w15);
        this.stopButton.Add(w14);
        this.musicButtonBox.Add(this.stopButton);
        Gtk.Box.BoxChild w22 = ((Gtk.Box.BoxChild)(this.musicButtonBox[this.stopButton]));
        w22.Position = 1;
        w22.Expand = false;
        w22.Fill = false;
        // Container child musicButtonBox.Gtk.Box+BoxChild
        this.previousButton = new Gtk.Button();
        this.previousButton.CanFocus = true;
        this.previousButton.Name = "previousButton";
        this.previousButton.UseUnderline = true;
        // Container child previousButton.Gtk.Container+ContainerChild
        Gtk.Alignment w23 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        w23.Name = "GtkAlignment";
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w24 = new Gtk.HBox();
        w24.Name = "GtkHBox";
        w24.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w25 = new Gtk.Image();
        w25.Name = "image37";
        w25.Pixbuf = Stetic.IconLoader.LoadIcon("stock_media-prev", 16);
        w24.Add(w25);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w27 = new Gtk.Label();
        w27.Name = "GtkLabel";
        w27.LabelProp = "";
        w24.Add(w27);
        w23.Add(w24);
        this.previousButton.Add(w23);
        this.musicButtonBox.Add(this.previousButton);
        Gtk.Box.BoxChild w31 = ((Gtk.Box.BoxChild)(this.musicButtonBox[this.previousButton]));
        w31.Position = 2;
        w31.Expand = false;
        w31.Fill = false;
        // Container child musicButtonBox.Gtk.Box+BoxChild
        this.nextButton = new Gtk.Button();
        this.nextButton.CanFocus = true;
        this.nextButton.Name = "nextButton";
        this.nextButton.UseUnderline = true;
        // Container child nextButton.Gtk.Container+ContainerChild
        Gtk.Alignment w32 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        w32.Name = "GtkAlignment";
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w33 = new Gtk.HBox();
        w33.Name = "GtkHBox";
        w33.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w34 = new Gtk.Image();
        w34.Name = "image38";
        w34.Pixbuf = Stetic.IconLoader.LoadIcon("stock_media-next", 16);
        w33.Add(w34);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w36 = new Gtk.Label();
        w36.Name = "GtkLabel";
        w36.LabelProp = "";
        w33.Add(w36);
        w32.Add(w33);
        this.nextButton.Add(w32);
        this.musicButtonBox.Add(this.nextButton);
        Gtk.Box.BoxChild w40 = ((Gtk.Box.BoxChild)(this.musicButtonBox[this.nextButton]));
        w40.Position = 3;
        w40.Expand = false;
        w40.Fill = false;
        // Container child musicButtonBox.Gtk.Box+BoxChild
        this.rewindButton = new Gtk.Button();
        this.rewindButton.CanFocus = true;
        this.rewindButton.Name = "rewindButton";
        this.rewindButton.UseUnderline = true;
        // Container child rewindButton.Gtk.Container+ContainerChild
        Gtk.Alignment w41 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        w41.Name = "GtkAlignment";
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w42 = new Gtk.HBox();
        w42.Name = "GtkHBox";
        w42.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w43 = new Gtk.Image();
        w43.Name = "image39";
        w43.Pixbuf = Stetic.IconLoader.LoadIcon("stock_media-rew", 16);
        w42.Add(w43);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w45 = new Gtk.Label();
        w45.Name = "GtkLabel";
        w45.LabelProp = "";
        w42.Add(w45);
        w41.Add(w42);
        this.rewindButton.Add(w41);
        this.musicButtonBox.Add(this.rewindButton);
        Gtk.Box.BoxChild w49 = ((Gtk.Box.BoxChild)(this.musicButtonBox[this.rewindButton]));
        w49.Position = 4;
        w49.Expand = false;
        w49.Fill = false;
        // Container child musicButtonBox.Gtk.Box+BoxChild
        this.fastfoward = new Gtk.Button();
        this.fastfoward.CanFocus = true;
        this.fastfoward.Name = "fastfoward";
        this.fastfoward.UseUnderline = true;
        // Container child fastfoward.Gtk.Container+ContainerChild
        Gtk.Alignment w50 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        w50.Name = "GtkAlignment";
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w51 = new Gtk.HBox();
        w51.Name = "GtkHBox";
        w51.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w52 = new Gtk.Image();
        w52.Name = "image40";
        w52.Pixbuf = Stetic.IconLoader.LoadIcon("stock_media-fwd", 16);
        w51.Add(w52);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w54 = new Gtk.Label();
        w54.Name = "GtkLabel";
        w54.LabelProp = "";
        w51.Add(w54);
        w50.Add(w51);
        this.fastfoward.Add(w50);
        this.musicButtonBox.Add(this.fastfoward);
        Gtk.Box.BoxChild w58 = ((Gtk.Box.BoxChild)(this.musicButtonBox[this.fastfoward]));
        w58.Position = 5;
        w58.Expand = false;
        w58.Fill = false;
        this.MainFixedWindow.Add(this.musicButtonBox);
        Gtk.Fixed.FixedChild w59 = ((Gtk.Fixed.FixedChild)(this.MainFixedWindow[this.musicButtonBox]));
        w59.X = 127;
        w59.Y = 120;
        // Container child MainFixedWindow.Gtk.Fixed+FixedChild
        this.songProgressBar = new Gtk.ProgressBar();
        this.songProgressBar.WidthRequest = 199;
        this.songProgressBar.Name = "songProgressBar";
        this.songProgressBar.Text = Mono.Unix.Catalog.GetString("00:00 / 00:00");
        this.MainFixedWindow.Add(this.songProgressBar);
        Gtk.Fixed.FixedChild w60 = ((Gtk.Fixed.FixedChild)(this.MainFixedWindow[this.songProgressBar]));
        w60.X = 132;
        w60.Y = 90;
        // Container child MainFixedWindow.Gtk.Fixed+FixedChild
        this.volumeScale = new Gtk.HScale(null);
        this.volumeScale.WidthRequest = 80;
        this.volumeScale.CanFocus = true;
        this.volumeScale.Name = "volumeScale";
        this.volumeScale.Adjustment.Upper = 1;
        this.volumeScale.Adjustment.PageIncrement = 0.5;
        this.volumeScale.Adjustment.StepIncrement = 0.1;
        this.volumeScale.Adjustment.Value = 1;
        this.volumeScale.DrawValue = false;
        this.volumeScale.Digits = 0;
        this.volumeScale.ValuePos = ((Gtk.PositionType)(2));
        this.MainFixedWindow.Add(this.volumeScale);
        Gtk.Fixed.FixedChild w61 = ((Gtk.Fixed.FixedChild)(this.MainFixedWindow[this.volumeScale]));
        w61.X = 3;
        w61.Y = 126;
        // Container child MainFixedWindow.Gtk.Fixed+FixedChild
        this.muteButton = new Gtk.Button();
        this.muteButton.CanFocus = true;
        this.muteButton.Name = "muteButton";
        this.muteButton.UseUnderline = true;
        // Container child muteButton.Gtk.Container+ContainerChild
        Gtk.Alignment w62 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        w62.Name = "GtkAlignment";
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w63 = new Gtk.HBox();
        w63.Name = "GtkHBox";
        w63.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w64 = new Gtk.Image();
        w64.Name = "image41";
        w64.Pixbuf = Stetic.IconLoader.LoadIcon("gtk-cancel", 16);
        w63.Add(w64);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w66 = new Gtk.Label();
        w66.Name = "GtkLabel";
        w66.LabelProp = "";
        w63.Add(w66);
        w62.Add(w63);
        this.muteButton.Add(w62);
        this.MainFixedWindow.Add(this.muteButton);
        Gtk.Fixed.FixedChild w70 = ((Gtk.Fixed.FixedChild)(this.MainFixedWindow[this.muteButton]));
        w70.X = 90;
        w70.Y = 120;
        // Container child MainFixedWindow.Gtk.Fixed+FixedChild
        this.volumeButton = new Gtk.Button();
        this.volumeButton.CanFocus = true;
        this.volumeButton.Name = "volumeButton";
        this.volumeButton.UseUnderline = true;
        // Container child volumeButton.Gtk.Container+ContainerChild
        Gtk.Alignment w71 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        w71.Name = "GtkAlignment";
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w72 = new Gtk.HBox();
        w72.Name = "GtkHBox";
        w72.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w73 = new Gtk.Image();
        w73.Name = "image42";
        w73.Pixbuf = Stetic.IconLoader.LoadIcon("stock_volume", 16);
        w72.Add(w73);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w75 = new Gtk.Label();
        w75.Name = "GtkLabel";
        w75.LabelProp = "";
        w72.Add(w75);
        w71.Add(w72);
        this.volumeButton.Add(w71);
        this.MainFixedWindow.Add(this.volumeButton);
        Gtk.Fixed.FixedChild w79 = ((Gtk.Fixed.FixedChild)(this.MainFixedWindow[this.volumeButton]));
        w79.X = 90;
        w79.Y = 120;
        // Container child MainFixedWindow.Gtk.Fixed+FixedChild
        this.npSong = new Gtk.Label();
        this.npSong.Name = "npSong";
        this.npSong.LabelProp = Mono.Unix.Catalog.GetString("Stopped");
        this.npSong.UseMarkup = true;
        this.MainFixedWindow.Add(this.npSong);
        Gtk.Fixed.FixedChild w80 = ((Gtk.Fixed.FixedChild)(this.MainFixedWindow[this.npSong]));
        w80.X = 115;
        w80.Y = 35;
        // Container child MainFixedWindow.Gtk.Fixed+FixedChild
        this.npByFrom = new Gtk.Label();
        this.npByFrom.WidthRequest = 231;
        this.npByFrom.Name = "npByFrom";
        this.npByFrom.LabelProp = Mono.Unix.Catalog.GetString("       ");
        this.npByFrom.UseMarkup = true;
        this.npByFrom.Wrap = true;
        this.MainFixedWindow.Add(this.npByFrom);
        Gtk.Fixed.FixedChild w81 = ((Gtk.Fixed.FixedChild)(this.MainFixedWindow[this.npByFrom]));
        w81.X = 121;
        w81.Y = 49;
        // Container child MainFixedWindow.Gtk.Fixed+FixedChild
        this.albumCoverImage = new Gtk.Image();
        this.albumCoverImage.Name = "albumCoverImage";
        this.albumCoverImage.Pixbuf = Stetic.IconLoader.LoadIcon("gtk-cdrom", 48);
        this.MainFixedWindow.Add(this.albumCoverImage);
        Gtk.Fixed.FixedChild w82 = ((Gtk.Fixed.FixedChild)(this.MainFixedWindow[this.albumCoverImage]));
        w82.X = 24;
        w82.Y = 62;
        // Container child MainFixedWindow.Gtk.Fixed+FixedChild
        this.tabbedNotebook = new Gtk.Notebook();
        this.tabbedNotebook.CanFocus = true;
        this.tabbedNotebook.Name = "tabbedNotebook";
        this.tabbedNotebook.CurrentPage = 1;
        this.tabbedNotebook.Scrollable = true;
        // Container child tabbedNotebook.Gtk.Notebook+NotebookChild
        this.searchVertBox = new Gtk.VBox();
        this.searchVertBox.Name = "searchVertBox";
        this.searchVertBox.Spacing = 6;
        // Container child searchVertBox.Gtk.Box+BoxChild
        this.searchTopHorBox = new Gtk.HBox();
        this.searchTopHorBox.Name = "searchTopHorBox";
        this.searchTopHorBox.Spacing = 6;
        this.searchTopHorBox.BorderWidth = ((uint)(4));
        // Container child searchTopHorBox.Gtk.Box+BoxChild
        this.searchSelectionType = Gtk.ComboBox.NewText();
        this.searchSelectionType.AppendText(Mono.Unix.Catalog.GetString("Song"));
        this.searchSelectionType.AppendText(Mono.Unix.Catalog.GetString("Artist"));
        this.searchSelectionType.AppendText(Mono.Unix.Catalog.GetString("Album"));
        this.searchSelectionType.AppendText(Mono.Unix.Catalog.GetString("Track #"));
        this.searchSelectionType.AppendText(Mono.Unix.Catalog.GetString("Year"));
        this.searchSelectionType.AppendText(Mono.Unix.Catalog.GetString("Genre"));
        this.searchSelectionType.AppendText(Mono.Unix.Catalog.GetString("Filename"));
        this.searchSelectionType.AppendText(Mono.Unix.Catalog.GetString("All Fields"));
        this.searchSelectionType.WidthRequest = 75;
        this.searchSelectionType.Name = "searchSelectionType";
        this.searchSelectionType.Active = 7;
        this.searchTopHorBox.Add(this.searchSelectionType);
        Gtk.Box.BoxChild w83 = ((Gtk.Box.BoxChild)(this.searchTopHorBox[this.searchSelectionType]));
        w83.Position = 0;
        w83.Expand = false;
        w83.Fill = false;
        // Container child searchTopHorBox.Gtk.Box+BoxChild
        this.searchEntry = new Gtk.Entry();
        this.searchEntry.WidthRequest = 246;
        this.searchEntry.HeightRequest = 23;
        this.searchEntry.HasDefault = true;
        this.searchEntry.CanFocus = true;
        this.searchEntry.Name = "searchEntry";
        this.searchEntry.IsEditable = true;
        this.searchEntry.InvisibleChar = '●';
        this.searchTopHorBox.Add(this.searchEntry);
        Gtk.Box.BoxChild w84 = ((Gtk.Box.BoxChild)(this.searchTopHorBox[this.searchEntry]));
        w84.Position = 1;
        this.searchVertBox.Add(this.searchTopHorBox);
        Gtk.Box.BoxChild w85 = ((Gtk.Box.BoxChild)(this.searchVertBox[this.searchTopHorBox]));
        w85.Position = 0;
        w85.Expand = false;
        w85.Fill = false;
        // Container child searchVertBox.Gtk.Box+BoxChild
        this.searchList = new Gtk.ScrolledWindow();
        this.searchList.WidthRequest = 329;
        this.searchList.HeightRequest = 358;
        this.searchList.CanFocus = true;
        this.searchList.Name = "searchList";
        this.searchList.HscrollbarPolicy = ((Gtk.PolicyType)(2));
        this.searchList.ShadowType = ((Gtk.ShadowType)(1));
        // Container child searchList.Gtk.Container+ContainerChild
        this.songListTree = new Gtk.TreeView();
        this.songListTree.CanFocus = true;
        this.songListTree.Name = "songListTree";
        this.songListTree.Reorderable = true;
        this.searchList.Add(this.songListTree);
        this.searchVertBox.Add(this.searchList);
        Gtk.Box.BoxChild w87 = ((Gtk.Box.BoxChild)(this.searchVertBox[this.searchList]));
        w87.Position = 1;
        // Container child searchVertBox.Gtk.Box+BoxChild
        this.searchBottomHorizonalBox = new Gtk.HBox();
        this.searchBottomHorizonalBox.Name = "searchBottomHorizonalBox";
        this.searchBottomHorizonalBox.Spacing = 6;
        this.searchBottomHorizonalBox.BorderWidth = ((uint)(2));
        // Container child searchBottomHorizonalBox.Gtk.Box+BoxChild
        this.searchAddButton = new Gtk.Button();
        this.searchAddButton.CanFocus = true;
        this.searchAddButton.Name = "searchAddButton";
        this.searchAddButton.UseUnderline = true;
        // Container child searchAddButton.Gtk.Container+ContainerChild
        Gtk.Alignment w88 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        w88.Name = "GtkAlignment";
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w89 = new Gtk.HBox();
        w89.Name = "GtkHBox";
        w89.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w90 = new Gtk.Image();
        w90.Name = "image43";
        w90.Pixbuf = Stetic.IconLoader.LoadIcon("gtk-add", 16);
        w89.Add(w90);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w92 = new Gtk.Label();
        w92.Name = "GtkLabel";
        w92.LabelProp = Mono.Unix.Catalog.GetString("Add");
        w92.UseUnderline = true;
        w89.Add(w92);
        w88.Add(w89);
        this.searchAddButton.Add(w88);
        this.searchBottomHorizonalBox.Add(this.searchAddButton);
        Gtk.Box.BoxChild w96 = ((Gtk.Box.BoxChild)(this.searchBottomHorizonalBox[this.searchAddButton]));
        w96.Position = 2;
        w96.Expand = false;
        w96.Fill = false;
        this.searchVertBox.Add(this.searchBottomHorizonalBox);
        Gtk.Box.BoxChild w97 = ((Gtk.Box.BoxChild)(this.searchVertBox[this.searchBottomHorizonalBox]));
        w97.Position = 2;
        w97.Expand = false;
        w97.Fill = false;
        this.tabbedNotebook.Add(this.searchVertBox);
        Gtk.Notebook.NotebookChild w98 = ((Gtk.Notebook.NotebookChild)(this.tabbedNotebook[this.searchVertBox]));
        w98.TabExpand = false;
        // Notebook tab
        this.searchMainLabel = new Gtk.Label();
        this.searchMainLabel.WidthRequest = 100;
        this.searchMainLabel.Name = "searchMainLabel";
        this.searchMainLabel.LabelProp = Mono.Unix.Catalog.GetString("Collection");
        this.tabbedNotebook.SetTabLabel(this.searchVertBox, this.searchMainLabel);
        // Container child tabbedNotebook.Gtk.Notebook+NotebookChild
        this.queueVertBox = new Gtk.VBox();
        this.queueVertBox.Name = "queueVertBox";
        this.queueVertBox.Spacing = 9;
        this.queueVertBox.BorderWidth = ((uint)(3));
        // Container child queueVertBox.Gtk.Box+BoxChild
        this.queueScrolledList = new Gtk.ScrolledWindow();
        this.queueScrolledList.CanFocus = true;
        this.queueScrolledList.Name = "queueScrolledList";
        this.queueScrolledList.VscrollbarPolicy = ((Gtk.PolicyType)(1));
        this.queueScrolledList.HscrollbarPolicy = ((Gtk.PolicyType)(1));
        this.queueScrolledList.ShadowType = ((Gtk.ShadowType)(1));
        // Container child queueScrolledList.Gtk.Container+ContainerChild
        this.queueTreeView = new Gtk.TreeView();
        this.queueTreeView.CanFocus = true;
        this.queueTreeView.Name = "queueTreeView";
        this.queueScrolledList.Add(this.queueTreeView);
        this.queueVertBox.Add(this.queueScrolledList);
        Gtk.Box.BoxChild w100 = ((Gtk.Box.BoxChild)(this.queueVertBox[this.queueScrolledList]));
        w100.Position = 0;
        // Container child queueVertBox.Gtk.Box+BoxChild
        this.queueBottomHorBox = new Gtk.HBox();
        this.queueBottomHorBox.Name = "queueBottomHorBox";
        this.queueBottomHorBox.Spacing = 6;
        // Container child queueBottomHorBox.Gtk.Box+BoxChild
        this.queueNewPlaylist = new Gtk.Button();
        this.queueNewPlaylist.CanFocus = true;
        this.queueNewPlaylist.Name = "queueNewPlaylist";
        // Container child queueNewPlaylist.Gtk.Container+ContainerChild
        Gtk.Alignment w101 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        w101.Name = "GtkAlignment";
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w102 = new Gtk.HBox();
        w102.Name = "GtkHBox";
        w102.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w103 = new Gtk.Image();
        w103.Name = "image44";
        w103.Pixbuf = Stetic.IconLoader.LoadIcon("gtk-file", 16);
        w102.Add(w103);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w105 = new Gtk.Label();
        w105.Name = "GtkLabel";
        w105.LabelProp = "";
        w102.Add(w105);
        w101.Add(w102);
        this.queueNewPlaylist.Add(w101);
        this.queueBottomHorBox.Add(this.queueNewPlaylist);
        Gtk.Box.BoxChild w109 = ((Gtk.Box.BoxChild)(this.queueBottomHorBox[this.queueNewPlaylist]));
        w109.Position = 0;
        w109.Expand = false;
        w109.Fill = false;
        // Container child queueBottomHorBox.Gtk.Box+BoxChild
        this.queueDeleteButton = new Gtk.Button();
        this.queueDeleteButton.CanFocus = true;
        this.queueDeleteButton.Name = "queueDeleteButton";
        this.queueDeleteButton.UseUnderline = true;
        // Container child queueDeleteButton.Gtk.Container+ContainerChild
        Gtk.Alignment w110 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        w110.Name = "GtkAlignment";
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w111 = new Gtk.HBox();
        w111.Name = "GtkHBox";
        w111.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w112 = new Gtk.Image();
        w112.Name = "image45";
        w112.Pixbuf = Stetic.IconLoader.LoadIcon("gtk-delete", 16);
        w111.Add(w112);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w114 = new Gtk.Label();
        w114.Name = "GtkLabel";
        w114.LabelProp = "";
        w111.Add(w114);
        w110.Add(w111);
        this.queueDeleteButton.Add(w110);
        this.queueBottomHorBox.Add(this.queueDeleteButton);
        Gtk.Box.BoxChild w118 = ((Gtk.Box.BoxChild)(this.queueBottomHorBox[this.queueDeleteButton]));
        w118.Position = 1;
        w118.Expand = false;
        w118.Fill = false;
        // Container child queueBottomHorBox.Gtk.Box+BoxChild
        this.label4 = new Gtk.Label();
        this.label4.Name = "label4";
        this.label4.LabelProp = Mono.Unix.Catalog.GetString("Playlist Name");
        this.queueBottomHorBox.Add(this.label4);
        Gtk.Box.BoxChild w119 = ((Gtk.Box.BoxChild)(this.queueBottomHorBox[this.label4]));
        w119.Position = 2;
        w119.Expand = false;
        w119.Fill = false;
        // Container child queueBottomHorBox.Gtk.Box+BoxChild
        this.queueEntryBox = new Gtk.Entry();
        this.queueEntryBox.WidthRequest = 3;
        this.queueEntryBox.CanFocus = true;
        this.queueEntryBox.Name = "queueEntryBox";
        this.queueEntryBox.IsEditable = true;
        this.queueEntryBox.InvisibleChar = '●';
        this.queueBottomHorBox.Add(this.queueEntryBox);
        Gtk.Box.BoxChild w120 = ((Gtk.Box.BoxChild)(this.queueBottomHorBox[this.queueEntryBox]));
        w120.Position = 3;
        // Container child queueBottomHorBox.Gtk.Box+BoxChild
        this.queueSaveButton = new Gtk.Button();
        this.queueSaveButton.CanFocus = true;
        this.queueSaveButton.Name = "queueSaveButton";
        this.queueSaveButton.UseUnderline = true;
        this.queueSaveButton.Label = Mono.Unix.Catalog.GetString("Save");
        this.queueBottomHorBox.Add(this.queueSaveButton);
        Gtk.Box.BoxChild w121 = ((Gtk.Box.BoxChild)(this.queueBottomHorBox[this.queueSaveButton]));
        w121.Position = 4;
        w121.Expand = false;
        w121.Fill = false;
        this.queueVertBox.Add(this.queueBottomHorBox);
        Gtk.Box.BoxChild w122 = ((Gtk.Box.BoxChild)(this.queueVertBox[this.queueBottomHorBox]));
        w122.Position = 1;
        w122.Expand = false;
        w122.Fill = false;
        this.tabbedNotebook.Add(this.queueVertBox);
        Gtk.Notebook.NotebookChild w123 = ((Gtk.Notebook.NotebookChild)(this.tabbedNotebook[this.queueVertBox]));
        w123.Position = 1;
        w123.TabExpand = false;
        // Notebook tab
        this.queueMainLabel = new Gtk.Label();
        this.queueMainLabel.WidthRequest = 100;
        this.queueMainLabel.Name = "queueMainLabel";
        this.queueMainLabel.LabelProp = Mono.Unix.Catalog.GetString("Current Songs");
        this.tabbedNotebook.SetTabLabel(this.queueVertBox, this.queueMainLabel);
        // Container child tabbedNotebook.Gtk.Notebook+NotebookChild
        this.playlistVertBox = new Gtk.VBox();
        this.playlistVertBox.Name = "playlistVertBox";
        this.playlistVertBox.Spacing = 6;
        this.playlistVertBox.BorderWidth = ((uint)(3));
        // Container child playlistVertBox.Gtk.Box+BoxChild
        this.playListScrolledWindow = new Gtk.ScrolledWindow();
        this.playListScrolledWindow.CanFocus = true;
        this.playListScrolledWindow.Name = "playListScrolledWindow";
        this.playListScrolledWindow.VscrollbarPolicy = ((Gtk.PolicyType)(1));
        this.playListScrolledWindow.HscrollbarPolicy = ((Gtk.PolicyType)(1));
        this.playListScrolledWindow.ShadowType = ((Gtk.ShadowType)(1));
        // Container child playListScrolledWindow.Gtk.Container+ContainerChild
        this.playListTreeView = new Gtk.TreeView();
        this.playListTreeView.CanFocus = true;
        this.playListTreeView.Name = "playListTreeView";
        this.playListScrolledWindow.Add(this.playListTreeView);
        this.playlistVertBox.Add(this.playListScrolledWindow);
        Gtk.Box.BoxChild w125 = ((Gtk.Box.BoxChild)(this.playlistVertBox[this.playListScrolledWindow]));
        w125.Position = 0;
        // Container child playlistVertBox.Gtk.Box+BoxChild
        this.playListBottomBox = new Gtk.HBox();
        this.playListBottomBox.Name = "playListBottomBox";
        this.playListBottomBox.Spacing = 6;
        // Container child playListBottomBox.Gtk.Box+BoxChild
        this.playListNewButton = new Gtk.Button();
        this.playListNewButton.CanFocus = true;
        this.playListNewButton.Name = "playListNewButton";
        this.playListNewButton.UseUnderline = true;
        // Container child playListNewButton.Gtk.Container+ContainerChild
        Gtk.Alignment w126 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        w126.Name = "GtkAlignment";
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w127 = new Gtk.HBox();
        w127.Name = "GtkHBox";
        w127.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w128 = new Gtk.Image();
        w128.Name = "image46";
        w128.Pixbuf = Stetic.IconLoader.LoadIcon("gtk-file", 16);
        w127.Add(w128);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w130 = new Gtk.Label();
        w130.Name = "GtkLabel";
        w130.LabelProp = Mono.Unix.Catalog.GetString("New");
        w130.UseUnderline = true;
        w127.Add(w130);
        w126.Add(w127);
        this.playListNewButton.Add(w126);
        this.playListBottomBox.Add(this.playListNewButton);
        Gtk.Box.BoxChild w134 = ((Gtk.Box.BoxChild)(this.playListBottomBox[this.playListNewButton]));
        w134.Position = 0;
        w134.Expand = false;
        w134.Fill = false;
        // Container child playListBottomBox.Gtk.Box+BoxChild
        this.playListLoadButton = new Gtk.Button();
        this.playListLoadButton.CanFocus = true;
        this.playListLoadButton.Name = "playListLoadButton";
        this.playListLoadButton.UseUnderline = true;
        // Container child playListLoadButton.Gtk.Container+ContainerChild
        Gtk.Alignment w135 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        w135.Name = "GtkAlignment";
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w136 = new Gtk.HBox();
        w136.Name = "GtkHBox";
        w136.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w137 = new Gtk.Image();
        w137.Name = "image47";
        w137.Pixbuf = Stetic.IconLoader.LoadIcon("gtk-directory", 16);
        w136.Add(w137);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w139 = new Gtk.Label();
        w139.Name = "GtkLabel";
        w139.LabelProp = Mono.Unix.Catalog.GetString("Load");
        w139.UseUnderline = true;
        w136.Add(w139);
        w135.Add(w136);
        this.playListLoadButton.Add(w135);
        this.playListBottomBox.Add(this.playListLoadButton);
        Gtk.Box.BoxChild w143 = ((Gtk.Box.BoxChild)(this.playListBottomBox[this.playListLoadButton]));
        w143.Position = 1;
        w143.Expand = false;
        w143.Fill = false;
        // Container child playListBottomBox.Gtk.Box+BoxChild
        this.playlistRenameButton = new Gtk.Button();
        this.playlistRenameButton.CanFocus = true;
        this.playlistRenameButton.Name = "playlistRenameButton";
        this.playlistRenameButton.UseUnderline = true;
        // Container child playlistRenameButton.Gtk.Container+ContainerChild
        Gtk.Alignment w144 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        w144.Name = "GtkAlignment";
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w145 = new Gtk.HBox();
        w145.Name = "GtkHBox";
        w145.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w146 = new Gtk.Image();
        w146.Name = "image48";
        w146.Pixbuf = Stetic.IconLoader.LoadIcon("gtk-edit", 16);
        w145.Add(w146);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w148 = new Gtk.Label();
        w148.Name = "GtkLabel";
        w148.LabelProp = Mono.Unix.Catalog.GetString("Edit");
        w148.UseUnderline = true;
        w145.Add(w148);
        w144.Add(w145);
        this.playlistRenameButton.Add(w144);
        this.playListBottomBox.Add(this.playlistRenameButton);
        Gtk.Box.BoxChild w152 = ((Gtk.Box.BoxChild)(this.playListBottomBox[this.playlistRenameButton]));
        w152.Position = 2;
        w152.Expand = false;
        w152.Fill = false;
        // Container child playListBottomBox.Gtk.Box+BoxChild
        this.playListDeleteButton = new Gtk.Button();
        this.playListDeleteButton.CanFocus = true;
        this.playListDeleteButton.Name = "playListDeleteButton";
        this.playListDeleteButton.UseUnderline = true;
        // Container child playListDeleteButton.Gtk.Container+ContainerChild
        Gtk.Alignment w153 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        w153.Name = "GtkAlignment";
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w154 = new Gtk.HBox();
        w154.Name = "GtkHBox";
        w154.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w155 = new Gtk.Image();
        w155.Name = "image49";
        w155.Pixbuf = Stetic.IconLoader.LoadIcon("gtk-delete", 16);
        w154.Add(w155);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w157 = new Gtk.Label();
        w157.Name = "GtkLabel";
        w157.LabelProp = Mono.Unix.Catalog.GetString("Delete");
        w157.UseUnderline = true;
        w154.Add(w157);
        w153.Add(w154);
        this.playListDeleteButton.Add(w153);
        this.playListBottomBox.Add(this.playListDeleteButton);
        Gtk.Box.BoxChild w161 = ((Gtk.Box.BoxChild)(this.playListBottomBox[this.playListDeleteButton]));
        w161.Position = 3;
        w161.Expand = false;
        w161.Fill = false;
        this.playlistVertBox.Add(this.playListBottomBox);
        Gtk.Box.BoxChild w162 = ((Gtk.Box.BoxChild)(this.playlistVertBox[this.playListBottomBox]));
        w162.PackType = ((Gtk.PackType)(1));
        w162.Position = 1;
        w162.Expand = false;
        w162.Fill = false;
        this.tabbedNotebook.Add(this.playlistVertBox);
        Gtk.Notebook.NotebookChild w163 = ((Gtk.Notebook.NotebookChild)(this.tabbedNotebook[this.playlistVertBox]));
        w163.Position = 2;
        w163.TabExpand = false;
        // Notebook tab
        this.playListMainLabel = new Gtk.Label();
        this.playListMainLabel.WidthRequest = 100;
        this.playListMainLabel.Name = "playListMainLabel";
        this.playListMainLabel.LabelProp = Mono.Unix.Catalog.GetString("Playlists");
        this.tabbedNotebook.SetTabLabel(this.playlistVertBox, this.playListMainLabel);
        this.MainFixedWindow.Add(this.tabbedNotebook);
        Gtk.Fixed.FixedChild w164 = ((Gtk.Fixed.FixedChild)(this.MainFixedWindow[this.tabbedNotebook]));
        w164.X = 10;
        w164.Y = 159;
        this.Add(this.MainFixedWindow);
        if ((this.Child != null)) {
            this.Child.ShowAll();
        }
        this.DefaultWidth = 562;
        this.DefaultHeight = 662;
        this.muteButton.Hide();
        this.Show();
        this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
        this.AddFolder.Activated += new System.EventHandler(this.OnAddFolderActivated);
        this.NewCollection.Activated += new System.EventHandler(this.OnNewCollectionActivated);
        this.Preferences.Activated += new System.EventHandler(this.OnPreferencesActivated);
        this.Exit1.Activated += new System.EventHandler(this.OnExit1Activated);
        this.AddFile.Activated += new System.EventHandler(this.OnAddFileActivated);
        this.About3.Activated += new System.EventHandler(this.OnAbout3Activated);
        this.playButton.Clicked += new System.EventHandler(this.OnPlayButtonClicked);
        this.stopButton.Clicked += new System.EventHandler(this.OnStopButtonClicked);
        this.previousButton.Clicked += new System.EventHandler(this.OnPreviousButtonClicked);
        this.nextButton.Clicked += new System.EventHandler(this.OnNextButtonClicked);
        this.rewindButton.Clicked += new System.EventHandler(this.OnRewindClicked);
        this.fastfoward.Clicked += new System.EventHandler(this.OnFastfowardClicked);
        this.volumeScale.ValueChanged += new System.EventHandler(this.OnVolumeScaleValueChanged);
        this.muteButton.Clicked += new System.EventHandler(this.OnMuteButtonClicked);
        this.volumeButton.Clicked += new System.EventHandler(this.OnVolumeButtonClicked);
        this.searchAddButton.Clicked += new System.EventHandler(this.OnSearchAddButtonClicked);
        this.queueNewPlaylist.Clicked += new System.EventHandler(this.OnQueueNewPlaylistClicked);
        this.queueDeleteButton.Clicked += new System.EventHandler(this.OnQueueDeleteButtonClicked);
        this.queueSaveButton.Clicked += new System.EventHandler(this.OnQueueSaveButtonClicked);
        this.playListNewButton.Clicked += new System.EventHandler(this.OnPlayListNewButtonClicked);
        this.playListLoadButton.Clicked += new System.EventHandler(this.OnPlayListLoadButtonClicked);
        this.playListDeleteButton.Clicked += new System.EventHandler(this.OnPlayListDeleteButtonClicked);
    }
}
